Carbon:
  IncludeAssets:
    Packages:
      zzz_JonnittoPhotoSwipe:
        Package: 'Jonnitto.PhotoSwipe'
        ConditionPrototype: 'Jonnitto.PhotoSwipe:IncludeCase'
        Path:
          File:
            CSS: 'Public'
            JS: 'Public'
        Live:
          # Dark.css and Light.css are included Themes
          Head:
            - Dark.css[async]
            - Main.js[defer]

Jonnitto:
  PhotoSwipe:
    preloaderMarkup: '<div class="pswp__preloader__icn"><div class="pswp__preloader__cut"><div class="pswp__preloader__donut"></div></div></div>'
    bgOpacity: 0.8
    alwaysInclude: false
    selector:
      onDocument: '[instanceof Jonnitto.PhotoSwipe:Include]'
      collection: '[instanceof Neos.Neos:ContentCollection]'
      content: '[instanceof Jonnitto.PhotoSwipe:Include],[instanceof Jonnitto.PhotoSwipe:LightboxMixin][lightbox=true],[instanceof Carbon.Image:Lightbox][lightbox=true]'
      lightbox: .lightbox
      gallery: body
    executeJS: true
    history: true
    show:
      topbar: true
      arrows: true
      caption: true
      close: true
      counter: true
      fullscreen: true
      modal: true
      preloader: true
      # If you want to turn all share buttons off at once you set it to false: (share: false)
      share:
        facebook: true
        twitter: true
        pinterest: true
        download: true
      zoom: true
      zoomEffect: true

Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          Jonnitto.PhotoSwipe:
            - 'NodeTypes/*'
    fusion:
      autoInclude:
        Jonnitto.PhotoSwipe: true
